namespace OkayegTeaTimeCSharp.Commands.CommandEnums
{
    public enum CommandType
    {
        Chatters,
        Check,
        Coinflip,
        Cookie,
        Count,
        CSharp,
        Emote,
        Fill,
        First,
        Fuck,
        Gachi,
        Help,
        Join,
        Last,
        Massping,
        Math,
        Nuke,
        Ping,
        Rafk,
        Rand,
        Remind,
        Search,
        Set,
        Spotify,
        Suggest,
        Tuck,
        Unset,
        Vanish,
        Yourmom
    }

    public enum AfkCommandType
    {
        Afk,
        Brb,
        Fat,
        Game,
        Gn,
        Lurk,
        Movie,
        Nap,
        Piss,
        Poof,
        Poop,
        School,
        Shower,
        Study,
        Work
    }
}